module.exports = Object.freeze({
    ACTION: {
        RENT: "RENT",
        SELL: "SELL"
    },
    FURNITURE: {
        Unfurnished: "Unfurnished",
        Semifurnished: "Semifurnished",
        Furnished: "Furnished"
    },
    BALCONIES: {
        Individual: "Individual",
        Persnal: "Personal",
        Attached: "Atteached",
    },
    FACING: {
        NORTH: "North",
        EAST: "East",
        WEST: "West",
        SOUTH: "South",
        NORTH_EAST: "North East",
        NORTH_WEST: "NORTH_North West",
        SOUTH_EAST: "South East",
        SOUTH_WEST: "South West",
    },
    VIEW: {
        GARDEN: "Garden",
        POOL: "Pool",
        PARK: "Park",
        MAIN_ROAD: "Mian road",
        EXPRESS_WAY: "Express way",
    },

    FLOORING: {
        MARBLE: "Marble",
        CEMENT: "Cement",
        GRANITE: "Granite",
        WOODEN: "Wooden",
        PVC: "PVC",
        VERIFIED: "Verified",
        CERAMIC: "Ceramic",
        ANTI_SKID: "Atnti Skid",
        TILES: "Tiles",
        MOSAIC: "Mosaic",
        CEMENT: "Cement",
    },
    ALLOWANCE: {
        BACHLORE: "Bachlore",
        FAMILY: "Family",
        BOTH: "Bachlore or Family",
        ONLY_GIRLS: "Only Girl's",
        ONLY_BOYS: "Only Boy's",
    },
    TYPE: {
        RESIDENTIAL: 'RESIDENTIAL',
        COMMERCIAL: 'COMMERCIAL',
    },
    RESIDENTIAL_SUB_TYPE: {
        APARTMENT: 'APARTMENT',
        PENT_HOUSE: 'PENT HOUSE',
        INDEPENDENT_HOUSE: ' INDEPENDENT HOUSE',
        VILLA: 'VILLA',
        PLOT: 'PLOT',
        BUILDER_FLOOR: 'BUILDER FLOOR',
    },
    RESIDENTIAL_ADDITIONAL_ROOMS: {
        POOJA: 'POOJA',
        SERVANT: "SERVANT",
        STUDY: 'STUDY',
        GUST: 'GUEST',
    },
    COMMERCIAL_SUB_TYPE: {
        OFFICE: 'OFFICE',
        SHOP: 'SHOP',
        LAND: 'LAND',
        SHOWROOM: 'SHOWROOM',
        WAREHOUSE: 'WAREHOUSE',
        INDUSTRIAL_PLOT: 'INDUSTRIAL PLOT',
        CO_WORKING_SPACE: 'CO-WORKING SPACE',
    },
    COMMERCIAL_ADDITIONAL_ROOMS: {
        MEETING_ROOM: 'MEETING ROOM',
        CONFERENCE_ROOM: 'CONFERENCE ROOM',
        BOARD_ROOM: 'BOARD ROOM',
        LOUNGE_AREA: 'LOUNGE AREA',
        RECEPTION_AREA: 'RECEPTION AREA',
        PANTRY: 'PANTRY',
        CABIN: 'CABIN',
        RESTROOM: 'RESTROOM',
        STORAGE_ROOM: 'STORAGE ROOM',
        SERVER_ROOM: 'SERVER ROOM',
        OPEN_WORKSPACE: 'OPEN WORKSPACE',
        TRAINING_ROOM: 'TRAINING ROOM',
        AUDITORIUM: 'AUDITORIUM',
        LIBRARY: 'LIBRARY',
        SHOWROOM: 'SHOWROOM',
        DISPLAY_AREA: 'DISPLAY AREA',
    },
    AREA_IN: {
        SQFT: 'SQFT',
        SQM: 'SQM',
        SQYD: 'SQYD',
        ACRE: 'ACRE',
    },
    // PERKS: {
    //     SPORTS: {
    //         Gymnasium: "Gymnasium",
    //         SwimmingPool: "SwimmingPool",
    //         KidsPool: "KidsPool",
    //         BadmintonCourt: "Badminton Court",
    //         TennisCourt: "Tennis Court",
    //         SquashCourt: "Squash Court",
    //         Football: "Football",
    //         Cricket: "Cricket",
    //         Basketball: "Basketball",
    //         Volleyball: "Volleyball",
    //         Yoga: "Yoga",
    //         Jogging: "Jogging",
    //         TableTennis: "Table Tennis",
    //         Park: "Park",
    //         School: "School"
    //     },
    //     SAFETY: {
    //         PowerBackup: "PowerBackup",
    //         Lift: "Lift",
    //         Security: "Security",
    //         FireFightingSystems: "FireFighting Systems",
    //         CCTV: "CCTV"
    //     },
    // },
})